name: Deploy Node Application

on: 
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t safump/nodejs-app:latest .
      - name: Publish Image to Docker Hub
        run: docker push safump/nodejs-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull safump/nodejs-app:latest 
      - name: Delete Old Container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' safump/nodejs-app
